// src/lib/components/snake-the-cat.svelte
<script lang="ts">
	import AvoidMouse from './avoid-mouse.svelte';

	let startingCoordinates = { x: 50, y: 50 };
</script>

<AvoidMouse {startingCoordinates}>
	<img
		src="/snake-the-cat.png"
		alt="A cat name snake"
		id="snake-the-cat"
		data-testid="snake-the-cat"
	/>
</AvoidMouse>

<style lang="postcss">
	#snake-the-cat {
		@apply w-72 max-w-full;
	}
</style>

// components/content/SnakeTheCat.vue
<template>
  <div id="name-container">
    <img id="snake-the-cat" src="/snake-the-cat.png" class="motion-safe:animate-bounce">
  </div>
</template>

<script>
export default {
  data() {
    return {};
  },
};
</script>

<style scoped>
#name-container {
  @apply w-full m-auto h-full overflow-hidden flex justify-center; 
}

#snake-the-cat {
  @apply m-10 mt-48;
}
</style>
